export enum BusinessEvents {
  // Connection events
  GATEWAY_CONNECT = "GATEWAY_CONNECT",
  GATEWAY_DISCONNECT = "GATEWAY_DISCONNECT",
  AUTH_FAILED = "AUTH_FAILED",

  // User presence events
  USER_ONLINE = "USER_ONLINE",
  USER_OFFLINE = "USER_OFFLINE",
  USER_KICK = "USER_KICK",

  // Document collaboration events
  DOCUMENT_UPDATE = "DOCUMENT_UPDATE",
  DOCUMENT_SYNC = "DOCUMENT_SYNC",
  DOCUMENT_CURSOR = "DOCUMENT_CURSOR",
  DOCUMENT_SELECTION = "DOCUMENT_SELECTION",

  // Subspace events
  SUBSPACE_UPDATE = "SUBSPACE_UPDATE",
  SUBSPACE_REORDER = "SUBSPACE_REORDER",

  // Workspace events
  WORKSPACE_UPDATE = "WORKSPACE_UPDATE",
  WORKSPACE_MEMBER_UPDATE = "WORKSPACE_MEMBER_UPDATE",
}
