## documents crud

### Create a document
POST http://localhost:5000/api/documents
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjUyNjY1MiwiZXhwIjoxNzMzMTMxNDUyfQ.U-g11SXLDch5DtlA7nRR03w2QIZUTd4qFZyVIWRPHIM

{
    "title": "test3",
    "content": "test3"
}

### Get directory tree
GET http://localhost:5000/api/documents/tree
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjUyNjY1MiwiZXhwIjoxNzMzMTMxNDUyfQ.U-g11SXLDch5DtlA7nRR03w2QIZUTd4qFZyVIWRPHIM

### Search document
GET http://localhost:5000/api/documents/search?keyword=D&sort=createdAt&order=desc&page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjUyNjY1MiwiZXhwIjoxNzMzMTMxNDUyfQ.U-g11SXLDch5DtlA7nRR03w2QIZUTd4qFZyVIWRPHIM

### Get all documents
GET http://localhost:5000/api/documents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjUyNjY1MiwiZXhwIjoxNzMzMTMxNDUyfQ.U-g11SXLDch5DtlA7nRR03w2QIZUTd4qFZyVIWRPHIM


### Get latest document
GET http://localhost:5000/api/documents/latest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjUyNjY1MiwiZXhwIjoxNzMzMTMxNDUyfQ.U-g11SXLDch5DtlA7nRR03w2QIZUTd4qFZyVIWRPHIM

### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "1@qq.com",
    "password": "Aa123456"
}

### Get document by id
GET http://localhost:5000/api/documents/cm3wmex050001yuf6uqujts5h
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjUyNjY1MiwiZXhwIjoxNzMzMTMxNDUyfQ.U-g11SXLDch5DtlA7nRR03w2QIZUTd4qFZyVIWRPHIM


### Resend email verification code
POST http://localhost:5000/api/auth/code/resend
Content-Type: application/json

{
    "email": "444@qq.com"
}

### Validate email verification code
POST http://localhost:5000/api/auth/code/validate
Content-Type: application/json

{
    "email": "1@qq.com",
    "code": "042408",
    "type": "register"
}

### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "1@qq.com", 
    "password": "Aa111111"
}

### Send email
POST http://localhost:5000/api/email
Content-Type: application/json

{
    "email": "yorkchan6228@gmail.com",
    "code": "123456"
}

### Protected route
GET http://localhost:5000/api/auth/userInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjUyNjY1MiwiZXhwIjoxNzMzMTMxNDUyfQ.U-g11SXLDch5DtlA7nRR03w2QIZUTd4qFZyVIWRPHIM

### Refresh token
POST http://localhost:5000/api/auth/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMzU3NzY5NCwiZXhwIjoxNzMzNTc3NzA0fQ.xbadG84cpYzvmF9M1xpX1uxa1UcD39eqFawuISvfTbA eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMzU3NzY5NCwiZXhwIjoxNzM0MTgyNDk0fQ.WZm13d_h9_6qqTuAiB3ya2gRZoJi3-wFsIwcJNj5-NU
