on:
  push:
    branches:
      # remove after testing
      - feature/test-deploy-github-action
      - test
      - staging
      - master

jobs:
  Deploy:
    name: Deploy to vm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "ENV=production" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/test' ]]; then
            echo "ENV=test" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/feature/test-deploy-github-action' ]]; then
            echo "ENV=production" >> $GITHUB_ENV
          else
            echo "ENV=test" >> $GITHUB_ENV
          fi

          # Write environment variables to build-job.env
          cat > scripts/builder/build-job.env << EOF
          # Environment variables
          ENV=${{ env.ENV }}

          # Docker Hub credentials
          DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD=${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKER_HUB_REPO=ideaforge-docker

          # Build related variables
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_AUTH_TOKEN_REACT=${{ secrets.SENTRY_AUTH_TOKEN_REACT }}
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}

          # tiptap auth token
          TIPTAP_AUTH_TOKEN=${{ secrets.TIPTAP_AUTH_TOKEN }}

          EOF


      - name: Build Docker image
        run: |
          make build

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: ubuntu
          host: ${{ secrets[format('VM_IP_{0}', env.ENV)] }}
          password: ${{ secrets[format('VM_PASSWORD_{0}', env.ENV)] }}
          script: |
            cd ~/deploy-scripts/idea-forge && \
            sh deploy.sh ${{ env.ENV }} ${{ env.IMAGE_TAG }}

      - name: Cleanup
        if: always()
        run: rm -rf ~/.ssh/
